### ISSUE TITLE
[Question] Are there plans to support local webserver or backend stores

### ISSUE THREAD

**Issue by jrasell** [puppetlabs/lumogon#43]
Firstly thanks for the great work on this project; after a brief time investigating lumogon it seems very helpful.

I have a couple of question about potential features of the project:

1. Are there plans/thoughts on having lumogon run a local webserver which can be used to display reports which are run on a periodic basis?
2. Are there plans/thoughts to add storage backends (S3 or GCS) where reports can be automatically uploaded?

Thanks,
jrasell

**Comment by garethr** [comment]
@jrasell thanks for trying Lumogon out. To your questions:

1. Regarding running reports on a periodic basis, that's possible right now if you want to, for instance, run report with a cron job or distributed cron solution or similar. It's definitely possible that we might add a persistent process so Lumogon could do this itself too. Rather than simply polling on some schedule we've also thought about sending reports based on the Docker events API, so as containers are launched or killed we can update in near-real-time. No fixed plans, but this is definitely the sort of direction we're considering.
1a. with regards displaying reports locally, we don't have immediate plans, but it's certainly a possibility. Building a single service we host makes iterating on it much easier, so we're starting there. But you can always redirect the report output to any endpoint you chose. This is actually overridable via an environment variable, eg. https://github.com/puppetlabs/lumogon/blob/master/Dockerfile.build#L3.

2. That's a neat idea. The intent with the service is to be able to provide richer interactions that would be possible just with raw data, so it's not something we've considered so far.

We basically envisage Lumogon as a relatively low-level piece of a puzzle, with hopefully a variety of different consumers above it over time. To work out if it's of interest we've started with the reporting service, but we'd love to understand the *why* behind the questions.

Also if anyone else spots this, if folks are interested in these sorts of features and maybe fancy trying to add them, we're happy to help.

**Comment by jrasell** [comment]
@garethr thanks very much for the answer. I don't have any scope to work on adding features currently but will certainly see if I can in the future.
